version: "3.9"
services:
  rubilink-node-genesis:
    environment:
    - RUBILINK_NODE_KEY_PATH=keys/genesisPrivateKey.pem
    - NODE_API_PORT=80
    - FIRST_SERVER_IP=146.190.121.59
    - P_2_P_PORT=5444
    image: rubilink-chain/rubilink-chain
    ports:
      - "5445:5445"
      - "5444:5444"
    networks:
      vpcbr:
        ipv4_address: 146.190.121.59
    command: python3.9 app.py

  rubilink-node-sakura  :
    environment:
    - RUBILINK_NODE_KEY_PATH=keys/sakuraPrivateKey.pem
    - NODE_API_PORT=81
    - FIRST_SERVER_IP=146.190.121.59
    - P_2_P_PORT=5444
    image: rubilink-chain/rubilink-chain
    depends_on:
      - rubilink-node-genesis
    ports:
      - "5446:5445"
      - "5447:5444"
    networks:
      vpcbr:
        ipv4_address: 146.190.121.59
    command: python3.9 main.py

  rubilink-node-bob:
    environment:
    - RUBILINK_NODE_KEY_PATH=keys/asukaPrivateKey.pem
    - NODE_API_PORT=82
    - FIRST_SERVER_IP=146.190.121.59
    - P_2_P_PORT=5444
    image: rubilink-chain/rubilink-chain
    depends_on:
      - rubilink-node-genesis
      - rubilink-node-sakura
    ports:
      - "5448:5445"
      - "5449:5444"
    networks:
      vpcbr:
        ipv4_address: 146.190.121.59
    command: python3.9 main.py

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 
         gateway: 146.190.121.59